function [ paths ] = altixPaths(  )
%Return paths

clusterRoot='\\komodo\SharedData\Fintan\';


%Paths
paths={clusterRoot,[clusterRoot 'Code-oldversion\matlab-helpers\'],[clusterRoot 'Code\'],...
    [clusterRoot 'Code-oldversion\sharePipe'],...
    [clusterRoot 'Code-oldversion\sockets'],...
    [clusterRoot 'Code-oldversion\mcgm'],...
    [clusterRoot 'Code-oldversion\motionTransfer'],...
    [clusterRoot 'Code-oldversion\common'],...
    [clusterRoot 'Code-oldversion\incrWarp'],...
    [clusterRoot 'Code-oldversion\firePCA'],...
    [clusterRoot 'Code-oldversion\cluster-utils'],...
    [clusterRoot 'Code-oldversion\tests'],...
    [clusterRoot 'Code-oldversion\mcgm'],...
    [clusterRoot 'Code-oldversion\misc-running']}
end

